# Generated by Django 2.1.7 on 2019-09-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
